[package]
name = "mars-servo"
version = "0.0.1"
authors = ["Josh Mcguigan"]
edition = "2018"

[[bin]]
name = "mars"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
toml = "0.5"
